# Generated by Django 4.2.2 on 2023-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(default="default.png", upload_to="profile_photos"),
        ),
    ]
