# Generated by Django 4.2.2 on 2023-07-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("studentregistration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
    ]
