# Generated by Django 4.2.2 on 2023-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("studentregistration", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "Module", "verbose_name_plural": "Modules"},
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ManyToManyField(related_name="modules", to="auth.group"),
        ),
    ]
