# Generated by Django 4.2.2 on 2023-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "studentregistration",
            "0003_alter_module_options_alter_registration_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="category",
            field=models.CharField(
                choices=[("Elective", "Elective"), ("Compulsory", "Compulsory")],
                max_length=255,
            ),
        ),
    ]
