# Generated by Django 4.2.2 on 2023-07-07 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "studentregistration",
            "0003_alter_module_options_alter_registration_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="course",
            new_name="courses",
        ),
    ]
