# Generated by Django 4.2.2 on 2023-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentregistration", "0004_alter_module_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(max_length=12),
        ),
    ]
