# Generated by Django 4.2.2 on 2023-07-10 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studentregistration", "0005_alter_module_code"),
        ("studentregistration", "0005_alter_registration_registration_date"),
    ]

    operations = []
