# Generated by Django 4.2.2 on 2023-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentregistration", "0006_merge_20230710_1522"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("student", "module"), name="unique_registration"
            ),
        ),
    ]
