# Generated by Django 4.2.2 on 2023-07-12 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_student_address_alter_student_city_and_more"),
        (
            "studentregistration",
            "0007_alter_registration_module_alter_registration_student",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("student", "module")},
        ),
    ]
