# Generated by Django 4.2.2 on 2023-07-12 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studentregistration", "0007_registration_unique_registration"),
        ("studentregistration", "0008_alter_registration_unique_together"),
    ]

    operations = []
