# Generated by Django 4.2.2 on 2023-07-29 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "studentregistration",
            "0010_alter_registration_unique_together_alter_module_code",
        ),
        (
            "studentregistration",
            "0011_alter_job_employer_logo_alter_job_job_apply_link_and_more",
        ),
    ]

    operations = []
