name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  AZURE_DB_NAME: ${{ secrets.AZURE_DB_NAME }}
  AZURE_DB_HOST: ${{ secrets.AZURE_DB_HOST }}
  AZURE_DB_PORT: ${{ secrets.AZURE_DB_PORT }}
  AZURE_DB_USER: ${{ secrets.AZURE_DB_USER }}
  AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report